# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. 1.0, 20.15.10

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./AzureStorageWrapper/
    - name: Build
      run: dotnet build ./AzureStorageWrapper/ --no-restore --configuration Release
    - name: Pack
      run: dotnet pack ./AzureStorageWrapper/AzureStorageWrapper.csproj -p:PackageVersion=${{ github.ref_name }} --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    - name: Publish NuGet
      run: dotnet nuget push ./AzureStorageWrapper/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
